import Head from "next/head";
import Image from "next/image";
import EmojiComponent from "../components/emoji/EmojiComponent";
import EmojiRating from "../components/emoji/EmojiRating";
import { LOGO } from "../constants/constant";
import useTranslation from "next-translate/useTranslation";
import { useRouter } from "next/router";


export default function Home() {
  let router = useRouter();
  let { t } = useTranslation();

  console.log(router);
  return (
    <div>
      
      <Head>
        <title>Jadroo Survey</title>
        <meta name="description" content="Generated by jadroo survey" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container xs:p-0">

        <header className="">
          <div className="flex items-center justify-between flex-1 mt-10">
            <div>
              <Image src={LOGO} width="150" height="50" />
            </div>
            <div>
  
            </div>
          </div>
        </header>

        <main>
          <div className="text-center xs:my-10 sm:my-16">
            <h2 className="mb-4 sm:text-3xl font-extrabold text-[#0159A2] xs:text-base ">
              User Experience Feedback Survey <br/>
              {t("common:greeting")}
            </h2>
          </div>

          <div className="overflow-hidden border rounded sm:p-6 sm:border xs:p-3">
            <EmojiRating
              listNumber="1"
              className="xs:w-5/5 xs:mb-6 sm:w-1/4 sm:mb-10"
              title="How satisfied are you with your overall experience of finding products and suppliers on Alibaba.com?"
            >
              <EmojiComponent />
            </EmojiRating>

            <EmojiRating
              listNumber="2"
              className="xs:w-5/5 xs:mb-6 sm:w-1/4 sm:mb-10"
              title="How satisfied are you with Alibaba.com homepage?"
            >
             <EmojiComponent />
            </EmojiRating>

            <EmojiRating
              listNumber="3"
              className="xs:w-5/5 xs:mb-6 sm:w-3/4 sm:mb-10"
              title="How satisfied are you with the following aspects of Alibaba.com Homepage?"
            >
              <div className="mt-4">
                  <div></div>
                  <div className="review-area">
                    <div className="xs:flex xs:flex-col sm:flex sm:flex-row justify-between px-4 py-3  rounded bg-[#ddd]">
                      <div className="justify-start flex-1"> Ability to find what I want</div>
                      <div className="flex justify-start flex-1 xs:mt-3 sm:mt-0">
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className=""><input type="radio" name="ability" className="w-4 h-4" /></div>
                      </div>
                    </div>
                    <div className="xs:flex xs:flex-col sm:flex sm:flex-row justify-between px-4 py-3  rounded bg-[#fff]">
                      <div className="justify-start flex-1"> Ability to find what I want</div>
                      <div className="flex justify-start flex-1 xs:mt-3 sm:mt-0">
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className=""><input type="radio" name="ability" className="w-4 h-4" /></div>
                      </div>
                    </div>
                    <div className="xs:flex xs:flex-col sm:flex sm:flex-row justify-between px-4 py-3  rounded bg-[#ddd]">
                      <div className="justify-start flex-1"> Ability to find what I want</div>
                      <div className="flex justify-start flex-1 xs:mt-3 sm:mt-0">
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className=""><input type="radio" name="ability" className="w-4 h-4" /></div>
                      </div>
                    </div>
                    <div className="xs:flex xs:flex-col sm:flex sm:flex-row justify-between px-4 py-3  rounded bg-[#fff]">
                      <div className="justify-start flex-1"> Ability to find what I want</div>
                      <div className="flex justify-start flex-1 xs:mt-3 sm:mt-0">
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className=""><input type="radio" name="ability" className="w-4 h-4" /></div>
                      </div>
                    </div>
                    <div className="xs:flex xs:flex-col sm:flex sm:flex-row justify-between px-4 py-3  rounded bg-[#ddd]">
                      <div className="justify-start flex-1"> Ability to find what I want</div>
                      <div className="flex justify-start flex-1 xs:mt-3 sm:mt-0">
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className=""><input type="radio" name="ability" className="w-4 h-4" /></div>
                      </div>
                    </div>
                    <div className="xs:flex xs:flex-col sm:flex sm:flex-row justify-between px-4 py-3  rounded bg-[#fff]">
                      <div className="justify-start flex-1"> Ability to find what I want</div>
                      <div className="flex justify-start flex-1 xs:mt-3 sm:mt-0">
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className="mr-6"><input type="radio" name="ability" className="w-4 h-4" /></div>
                        <div className=""><input type="radio" name="ability" className="w-4 h-4" /></div>
                      </div>
                    </div>
                  </div>
              </div>
            </EmojiRating>

            <EmojiRating
              listNumber="4"
              className="xs:w-5/5 xs:mb-6 sm:w-3/4 sm:mb-10"
              title="Which of the following best describes your primary use of Alibaba.com?"
            >
               <div className="grid gap-1">
                 <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    Sell products on Alibaba.com
                  </label>
                 </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    Find products for a business
                  </label>
                </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    Find products for non-business
                  </label>
                </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    Other (please specify)
                  </label>
                </div>
               </div>

            </EmojiRating>

            <EmojiRating
              listNumber="5"
              className="xs:w-5/5 xs:mb-6 sm:w-2/6 sm:mb-10"
              title="How much (in U.S. dollar terms) do you/ your organization source on an annual basis (including on and outside Alibaba)?"
            >

              <div className="grid gap-1">
                 <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    Less than $10,000
                  </label>
                 </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    $10,001 - $100,000
                  </label>
                </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    $100,001 - $500,000
                  </label>
                </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    $500,001 - $1,000,000
                  </label>
                </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    $1,000,001 - $5,000,000
                  </label>
                </div>
                <div>
                  <label className="inline-flex items-center">
                    <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                    More than $5,000,000
                  </label>
                </div>
              </div>

            </EmojiRating>

            <EmojiRating
              listNumber="6"
              title="What do you want to do at Alibaba.com homepage? Is there anything we can do to improve ?"
              className="xs:w-1/1 sm:w-3/4"
            >
              <textarea name="" rows="5" className="w-full mt-4 mb-6 border rounded"></textarea>
              <button className="px-4 py-2 rounded text-white font-medium mt-4 bg-[#025AA2] hover:bg-[#027ce0]">Submit</button>
            </EmojiRating>

          </div>
        </main>
      </div>
      
      <footer className="mt-12 border-t shadow-2xl bg-[#f1f2f3]">
        <div className="sm:h-[230px] xs:h-[180px] pt-12">
            <div className="text-center">
              <p className="xs:text-[8px] sm:text-[14px]  my-2 text-black">AliExpress | 1688.com | Tmall Taobao World | Alipay | Lazada</p>
              <p className="xs:text-[8px] sm:text-[14px]  my-2 text-black">Browse Alphabetically: Onetouch | Showroom | Country Search | Suppliers | Affiliate</p>
              <p className="xs:text-[8px] sm:text-[14px]  my-2 text-black">Product Listing Policy - Intellectual Property Protection - Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
              <p className="xs:text-[8px] sm:text-[14px]  my-2 text-black">© 1999-2021 Alibaba.com. All rights reserved. 浙公网安备 33010002000092号 浙B2-20120091-4</p>
            </div>
        </div>
        {/* <ul>
          {router.locales.map((locale) => (
            <li key={locale}>
              <Link href={router.asPath} locale={locale}>
                <a>{locale}</a>
              </Link>
            </li>
          ))}
        </ul> */}
      </footer>
    </div>
  );
}
 {/* bg-[#080027] */}