import Head from "next/head";
import Image from "next/image";
import EmojiComponent from "../components/emoji/EmojiComponent";
import EmojiRating from "../components/emoji/EmojiRating";
import { LOGO } from "../constants/constant";
import ReactStars from "react-rating-stars-component";
import { useState } from "react";

export default function ProductReview() {

  const [switchToggle, setSwitchToggle] = useState(false);

  const ratingChanged = (newRating) => {
    console.log(newRating);
  };
   

  return (
    <div>
      <Head>
        <title>Jadroo Survey</title>
        <meta name="description" content="Generated by jadroo survey" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container xs:p-0">

        <header className="">
          <div className="flex items-center justify-between mt-10">

            <div className="flex-1">
              <Image src={LOGO} width="150" height="50" />
            </div>

            <div className="flex items-center justify-end flex-1 h-[50px]">
              <label htmlFor="toogleA" className="flex items-center cursor-pointer">
                <div className="mr-3 font-medium text-[20px] text-gray-700">{switchToggle === false ? 'EN' : 'BN' }</div>
                <div className="relative">
                  <input id="toogleA" onClick={ () => setSwitchToggle(!switchToggle)} type="checkbox" className="sr-only" />
                  <div className="w-10 h-4 bg-gray-400 rounded-full shadow-inner" />
                  <div className="absolute w-6 h-6 transition bg-[#0159A2] rounded-full shadow dot -left-1 -top-1" />
                </div>
              </label>
            </div>
            
          </div>
        </header>

        <main>
          <div className="overflow-hidden border rounded xs:my-8 sm:my-16 sm:p-6 sm:border xs:p-3">
            <EmojiRating
              listNumber="1"
              className="xs:w-5/5 xs:mb-6 sm:w-1/4 sm:mb-10"
              title="How satisfied are you with the current product detail page in accomplishing your purpose?"
            >
              <ReactStars
                count={5}
                onChange={ratingChanged}
                size={60}
                isHalf={true}
                emptyIcon={<i className="far fa-star"></i>}
                halfIcon={<i className="fa fa-star-half-alt"></i>}
                fullIcon={<i className="fa fa-star"></i>}
                activeColor="#ffd700"
              />
            </EmojiRating>

            <EmojiRating
              listNumber="2"
              className="xs:w-5/5 xs:mb-6 sm:w-3/4 sm:mb-10"
              title="What are the problems with the current detail page? Please describe your problems and suggestions."
            >
              <textarea name="" placeholder="Place input your answer here" rows="5" className="w-full p-3 mt-4 border rounded"></textarea>
            </EmojiRating>

            <EmojiRating
              listNumber="3"
              className="xs:w-5/5 xs:mb-6 sm:w-2/6 sm:mb-10"
              title="If we want to learn more about your experience on Alibaba.com, can we get in touch with you for an interview? Incentives would be provided to participants who complete the interview."
            >
              <div className="">
                  <div></div>
                  <div className="review-area">

                    <label className="justify-between p-3 border border-gray-500 rounded xs:flex xs:flex-col sm:flex sm:flex-row hover:border hover:border-blue-600">
                      <div className="flex justify-start mt-0">
                        <div className="flex items-center mr-2">
                          <input type="radio" name="ability_" className="w-4 h-4 mr-2" />
                          Yes
                        </div>
                      </div>
                    </label>

                    <label className="justify-between p-3 mt-4 border border-gray-500 rounded xs:flex xs:flex-col sm:flex sm:flex-row hover:border hover:border-blue-600">
                      <div className="flex justify-start mt-0">
                        <div className="flex items-center mr-2">
                          <input type="radio" name="ability_" className="w-4 h-4 mr-2" />
                          No
                        </div>
                      </div>
                    </label>

                  </div>
              </div>
            </EmojiRating>

            <EmojiRating
              listNumber="4"
              className="xs:w-5/5 xs:mb-6 sm:w-3/4 sm:mb-10"
              title="Which of the following best describes your primary use of Alibaba.com?"
            >
              <div className="sm:grid sm:grid-cols-2 sm:gap-4 xs:grid xs:grid-cols-1 xs:gap-4">
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                  Sell products on Alibaba.com
                </label>

                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                  Find products for a business
                </label>
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                  Find products for non-business 
                </label>
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied" className="w-4 h-4 my-2 mr-2" />
                  Other (please specify)
                </label>

              </div>

            </EmojiRating>

            <EmojiRating
              listNumber="5"
              className="xs:w-5/5 xs:mb-6 sm:w-3/4 sm:mb-10 sm:mt-6"
              title="How much (in U.S. dollar terms) do you/ your organization source on an annual basis (including on and outside Alibaba)?"
            >
              <div className="sm:grid sm:grid-cols-2 sm:gap-4 xs:grid xs:grid-cols-1 xs:gap-4">
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                
                <label className="inline-flex items-center p-3 bg-gray-200 border rounded hover:border hover:border-blue-600">
                  <input type="radio" name="satisfied_review" className="w-4 h-4 my-2 mr-2 " />
                  More than $5,000,000
                </label>
                

              </div>

              <div className="xs:mt-4 sm:mt-10">
                <button className="px-10 py-2 rounded text-white font-medium mt-4 bg-[#025AA2] hover:bg-[#027ce0]">Submit</button>
              </div>
            </EmojiRating>

          </div>
        </main>
      </div>
    </div>
  );
}
 {/* bg-[#080027] */}